---
title: "MATH 216 Homework 2 Shiny App"
author: "Alexander Pastora"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
movies <- movies %>% filter(is.na(budget)==FALSE)
inputPanel({
  
  radioButtons("genre",label="Choose a Genre:", choices = c("Comedy","Non-Comedy"))
  
})

renderPlot({
  T_or_F <- "Comedy" == input$genre
  
  ggplot(data=movies %>% filter(Comedy==T_or_F) %>%  select_("rating","budget", "Comedy"), aes(x=budget, y=rating))+geom_point() + scale_x_log10()
  
  })
```
